=== sridev24/workingonit/configo/src/java/resources/configo.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
  - Copyright 2009 Vladimir Ritz Bossicard
  -
  - This file is part of Configo.
  -
  - Configo is free software: you can redistribute it and/or modify it under the
  - terms of the GNU General Public License as published by the Free Software
  - Foundation, either version 3 of the License, or (at your option) any later
  - version.
  -
  - This program is distributed in the hope that it will be useful, but WITHOUT
  - ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  - FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
  - more details.
  -
  - You should have received a copy of the GNU General Public License along with
  - this program. If not, see <http://www.gnu.org/licenses/>.
  -
  - Author      : Vladimir Ritz Bossicard
  - Version     : $Revision: 120 $
  - Last edit   : $Date: 2009-04-20 21:09:15 +0200 (Mon, 20 Apr 2009) $
  - Last editor : $Author: vbossica $
  -->

<!ELEMENT configuration ( name, description, modules ) >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT modules ( module+ ) >

<!ELEMENT module ( description | name | properties )* >

<!ELEMENT properties ( property+ ) >

<!ELEMENT property ( description | key | name )* >

<!ELEMENT key ( #PCDATA ) >

=== sridev24/workingonit/configo/src/java/resources/configo-config.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--
  - Copyright 2009 Vladimir Ritz Bossicard
  -
  - This file is part of Configo.
  -
  - Configo is free software: you can redistribute it and/or modify it under the
  - terms of the GNU General Public License as published by the Free Software
  - Foundation, either version 3 of the License, or (at your option) any later
  - version.
  -
  - This program is distributed in the hope that it will be useful, but WITHOUT
  - ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
  - FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
  - more details.
  -
  - You should have received a copy of the GNU General Public License along with
  - this program. If not, see <http://www.gnu.org/licenses/>.
  -
  - Author      : Vladimir Ritz Bossicard
  - Version     : $Revision: 131 $
  - Last edit   : $Date: 2009-04-21 13:26:37 +0200 (Tue, 21 Apr 2009) $
  - Last editor : $Author: vbossica $
  -->

<!DOCTYPE configuration PUBLIC "-//WorkingOnIt/Configo Configuration DTD 1.0//EN" "configo.dtd" >

<configuration>
    <name>Configo</name>
    <description>Default configuration</description>
    <modules>
        <module>
            <name>Module name</name>
            <description>Module description</description>
            <properties>
                <property>
                    <name>Prop name</name>
                    <description>Prop description</description>
                    <key>prop.key</key>
                </property>
            </properties>
        </module>
    </modules>
</configuration>

=== sridev24/workingonit/configo/test/sample/resources/configo-config.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE configuration PUBLIC "-//WorkingOnIt/Configo Configuration DTD 1.0//EN" "configo.dtd" >

<configuration>
    <name>ACME KitchenSink Configuration</name>
    <description>ACME KitchenSink is a state of the art software 
produced by AcmeSoft Inc. that is able to do everything.</description>

    <modules>
        <module>
            <name>Interfaces</name>
            <description>Values needed for retrieving and storing data</description>
            <properties>
                <property>
                    <name>web service url</name>
                    <description>URL of the web service (e.g. http://server:host/acmesoft)</description>
                    <key>com.acme.kitchensink.wsurl</key>
                </property>
                <property>
                    <name>output directory</name>
                    <description>absolute path of the directry where files are saved</description>
                    <key>com.acme.kitchensink.outputdir</key>
                </property>
            </properties>
        </module>
    </modules>
    
</configuration>

=== sridev24/workingonit/configo/test/java/resources/definition.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE configuration PUBLIC "-//WorkingOnIt/Configo Configuration DTD 1.0//EN" "configo.dtd" >

<configuration>
    <name>Sample Application</name>
    <modules>
        <module>
            <name>Module A</name>
            <description>Module's description</description>
            <properties>
                <property>
                    <name>Name 1</name>
                    <description>Property's description</description>
                    <key>key1</key>
                </property>
            </properties>
        </module>
        <module>
            <name>Module B</name>
            <properties>
                <property>
                    <key>key2</key>
                </property>
            </properties>
        </module>
    </modules>
</configuration>
